export default [
  {
    title: "El árbol mágico"
    ,
    description:
      "Hace mucho mucho tiempo, un niño paseaba por un prado en cuyo centro encontró un árbol con un cartel que decía: soy un árbol encantado, si dices las palabras mágicas, lo verás.El niño trató de acertar el hechizo, y probó con abracadabra, supercalifragilisticoespialidoso, tan-ta-ta-chán, y muchas otras, pero nada. Rendido, se tiró suplicante, diciendo: por favor, arbolito!!, y entonces, se abrió una gran puerta en el árbol. Todo estaba oscuro, menos un cartel que decía: sigue haciendo magia. Entonces el niño dijo ¡¡Gracias, arbolito!!, y se encendió dentro del árbol una luz que alumbraba un camino hacia una gran montaña de juguetes y chocolate. El niño pudo llevar a todos sus amigos a aquel árbol y tener la mejor fiesta del mundo, y por eso se dice siempre que por favor y gracias, son las palabras mágicas",
    avatarUrl:
      "https://c3352096.ssl.cf0.rackcdn.com/el-arbol-magico-150height.jpg",
    imageUrl:
      "https://c3352096.ssl.cf0.rackcdn.com/el-arbol-magico-150height.jpg",
  },
  {
    title: "La princesa de fuego",
    description:
      "Hubo una vez una princesa increíblemente rica, bella y sabia. Cansada de pretendientes falsos que se acercaban a ella para conseguir sus riquezas, hizo publicar que se casaría con quien le llevase el regalo más valioso, tierno y sincero a la vez. El palacio se llenó de flores y regalos de todos los tipos y colores, de cartas de amor incomparables y de poetas enamorados. Y entre todos aquellos regalos magníficos, descubrió una piedra; una simple y sucia piedra. Intrigada, hizo llamar a quien se la había regalado. A pesar de su curiosidad, mostró estar muy ofendida cuando apareció el joven, y este se explicó diciendo Esa piedra representa lo más valioso que os puedo regalar, princesa: es mi corazón. Y también es sincera, porque aún no es vuestro y es duro como una piedra. Sólo cuando se llene de amor se ablandará y será más tierno que ningún otro.El joven se marchó tranquilamente, dejando a la princesa sorprendida y atrapada. Quedó tan enamorada que llevaba consigo la piedra a todas partes, y durante meses llenó al joven de regalos y atenciones, pero su corazón seguía siendo duro como la piedra en sus manos. Desanimada, terminó por arrojar la piedra al fuego; al momento vio cómo se deshacía la arena, y de aquella piedra tosca surgía una bella figura de oro. Entonces comprendió que ella misma tendría que ser como el fuego, y transformar cuanto tocaba separando lo inútil de lo importante.Durante los meses siguientes, la princesa se propuso cambiar en el reino, y como con la piedra, dedicó su vida, su sabiduría y sus riquezas a separar lo inútil de lo importante. Acabó con el lujo, las joyas y los excesos, y las gentes del país tuvieron comida y libros. Cuantos trataban con la princesa salían encantados por su carácter y cercanía, y su sola prensencia transmitía tal calor humano y pasión por cuanto hacía, que comenzaron a llamarla cariñosamente La princesa de fuego.Y como con la piedra, su fuego deshizo la dura corteza del corazón del joven, que tal y como había prometido, resultó ser tan tierno y justo que hizo feliz a la princesa hasta el fin de sus días",
    avatarUrl:
      "https://c3352096.ssl.cf0.rackcdn.com/corazon-de-fuego.jpg",
    imageUrl:
      "https://c3352096.ssl.cf0.rackcdn.com/corazon-de-fuego.jpg",
  },
  {
    title: "El cohete de papel",
    description:
      "Había una vez un niño cuya mayor ilusión era tener un cohete y dispararlo hacia la luna, pero tenía tan poco dinero que no podía comprar ninguno. Un día, junto a la acera descubrió la caja de uno de sus cohetes favoritos, pero al abrirla descubrió que sólo contenía un pequeño cohete de papel averiado, resultado de un error en la fábrica. El niño se apenó mucho, pero pensando que por fin tenía un cohete, comenzó a preparar un escenario para lanzarlo. Durante muchos días recogió papeles de todas las formas y colores, y se dedicó con toda su alma a dibujar, recortar, pegar y colorear todas las estrellas y planetas para crear un espacio de papel. Fue un trabajo dificilísimo, pero el resultado final fue tan magnífico que la pared de su habitación parecía una ventana abierta al espacio sideral.Desde entonces el niño disfrutaba cada día jugando con su cohete de papel, hasta que un compañero visitó su habitación y al ver aquel espectacular escenario, le propuso cambiárselo por un cohete auténtico que tenía en casa. Aquello casi le volvió loco de alegría, y aceptó el cambio encantado.Desde entonces, cada día, al jugar con su cohete nuevo, el niño echaba de menos su cohete de papel, con su escenario y sus planetas, porque realmente disfrutaba mucho más jugando con su viejo cohete. Entonces se dio cuenta de que se sentía mucho mejor cuando jugaba con aquellos juguetes que él mismo había construido con esfuerzo e ilusión.Y así, aquel niño empezó a construir él mismo todos sus juguetes, y cuando creció, se convirtió en el mejor juguetero del mundo.",
    avatarUrl:
      "https://c3352096.ssl.cf0.rackcdn.com/el-cohete-de-papel-150height.jpg",
    imageUrl:
      "https://c3352096.ssl.cf0.rackcdn.com/el-cohete-de-papel-150height.jpg",
  },
  {
    title: "El niño que insultaba demasiado",
    description:
      "- ¡Oh, Gran Mago! ¡Ha ocurrido una tragedia! El pequeño Manu ha robado el elixir con el hechizo Lanzapalabras.- ¿Manu? ¡Pero si ese niño es un maleducado que insulta a todo el mundo! Esto es terrible.. ¡hay que detenerlo antes de que lo beba!      Pero ya era demasiado tarde. Manu recorría la ciudad insultado a todos solo para ver cómo sus palabras tomaban forma y sus letras se lanzaban contra quien fuera como fantasmas que, al tocarlos, los atravesaban y los transformaban en aquello que hubiera dicho Manu. Así, siguiendo el rastro de tontos, feos, idiotas, gordos y viejos, el mago y sus ayudantes no tardaron en dar con él.      - ¡Deja de hacer eso, Manu! Estás fastidiando a todo el mundo. Por favor, bebe este otro elixir para deshacer el hechizo antes de que sea tarde.- ¡No quiero! ¡Esto es muy divertido! Y soy el único que puede hacerlo ¡ja, ja, ja, ja! ¡Tontos! ¡Lelos! ¡Calvos! ¡Viejos! - gritó haciendo una metralleta de insultos.- Tengo una idea, maestro - digo uno de los ayudantes mientras escapaban de las palabras de Manu- podríamos dar el elixir a todo el mundo.- ¿Estás loco? Eso sería terrible. Si estamos así y solo hay un niño insultando, ¡imagínate cómo sería si lo hiciera todo el mundo! Tengo que pensar algo. En los siete días que el mago tardó en inventar algo, Manu llegó a convertirse en el dueño de la ciudad, donde todos le servían y obedecían por miedo. Por suerte, el mago pudo usar su magia para llegar hasta Manu durante la noche y darle unas gotas de la nueva poción mientras dormía.Manu se despertó dispuesto a divertirse a costa de los demás. Pero en cuanto entró el mayordomo llevando el desayuno, cientos de letras volaron hacia Manu, formando una ráfaga de palabras de las que solo distinguió “caprichoso”, “abusón” y “maleducado”. Al contacto con su piel, las letras se disolvieron, provocándole un escozor terrible.El niño gritó, amenazó y usó terribles palabras, pero pronto comprendió que el mayordomo no había visto nada. Ni ninguno de los que surgieron nuevas ráfagas de letras ácidas dirigidas hacia él. En un solo día aquello de los hechizos de palabras pasó de ser lo más divertido a ser lo peor del mundo.- Será culpa del mago. Mañana iré a verle para que me quite el hechizo.Pero por más que lloró y pidió perdón, era demasiado tarde para el antídoto.- Tendrás que aprender a vivir con tus dos hechizos: lanzapalabras y recibepensamientos. Bien usados podrían ser útiles… Manu casi no podía salir a la calle. Se había portado tan mal con todos que, aunque no se lo dijeran por miedo, en el fondo pensaban cosas horribles de él y cuando esos pensamientos le tocaban eran como el fuego. Por eso empezó a estar siempre solo.Un día, una niña pequeña vio su aspecto triste y sintió lástima. La pequeña pensó que le gustaría ser amiga de aquel niño y, cuando aquel pensamiento tocó la piel de Manu, en lugar de dolor le provocó una sensación muy agradable. Manu tuvo una idea.",
    avatarUrl:
      "https://c3352096.ssl.cf0.rackcdn.com/el-nino-que-insultaba-demasiado-150height.jpg",
    imageUrl:
      "https://c3352096.ssl.cf0.rackcdn.com/el-nino-que-insultaba-demasiado-150height.jpg",
  },

];
